{
 "title": "go",
 "panels": [
  {
   "title": "go_gc_duration_seconds",
   "type": "timeseries",
   "description": "A summary of the pause duration of garbage collection cycles.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "description": "Number of goroutines that currently exist.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_info",
   "type": "timeseries",
   "description": "Information about the Go environment.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_info{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_threads",
   "type": "timeseries",
   "description": "Number of OS threads created.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_threads{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "go_memstats",
 "panels": [
  {
   "title": "go_memstats_buck_hash_sys_bytes",
   "type": "timeseries",
   "description": "Number of bytes used by the profiling bucket hash table.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_gc_sys_bytes",
   "type": "timeseries",
   "description": "Number of bytes used for garbage collection system metadata.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_gc_sys_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_last_gc_time_seconds",
   "type": "timeseries",
   "description": "Number of seconds since 1970 of last garbage collection.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_memstats_last_gc_time_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "timeseries",
   "description": "Number of bytes allocated and still in use.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_stack_inuse_bytes",
   "type": "timeseries",
   "description": "Number of bytes in use by the stack allocator.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_stack_sys_bytes",
   "type": "timeseries",
   "description": "Number of bytes obtained from system for stack allocator.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_sys_bytes",
   "type": "timeseries",
   "description": "Number of bytes obtained from system.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_other_sys_bytes",
   "type": "timeseries",
   "description": "Number of bytes used for other system allocations.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_other_sys_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_mcache_inuse_bytes",
   "type": "timeseries",
   "description": "Number of bytes in use by mcache structures.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_mcache_sys_bytes",
   "type": "timeseries",
   "description": "Number of bytes used for mcache structures obtained from system.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mcache_sys_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_frees_total",
   "type": "timeseries",
   "description": "Total number of frees.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "go_memstats_next_gc_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes when next garbage collection will take place.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_mspan_sys_bytes",
   "type": "timeseries",
   "description": "Number of bytes used for mspan structures obtained from system.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_sys_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_mspan_inuse_bytes",
   "type": "timeseries",
   "description": "Number of bytes in use by mspan structures.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_mallocs_total",
   "type": "timeseries",
   "description": "Total number of mallocs.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "go_memstats_lookups_total",
   "type": "timeseries",
   "description": "Total number of pointer lookups.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "go_memstats_heap",
 "panels": [
  {
   "title": "go_memstats_heap_alloc_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes allocated and still in use.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_heap_released_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes released to OS.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_heap_inuse_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes that are in use.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes obtained from system.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_heap_objects",
   "type": "timeseries",
   "description": "Number of allocated objects.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "go_memstats_heap_idle_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes waiting to be used.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "net_conntrack",
 "panels": [
  {
   "title": "net_conntrack_listener_conn_accepted_total",
   "type": "timeseries",
   "description": "Total number of connections opened to the listener of a given name.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_conntrack_listener_conn_accepted_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "net_conntrack_listener_conn_closed_total",
   "type": "timeseries",
   "description": "Total number of connections closed that were made to the listener of a given name.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_conntrack_listener_conn_closed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "net_conntrack_dialer_conn",
 "panels": [
  {
   "title": "net_conntrack_dialer_conn_closed_total",
   "type": "timeseries",
   "description": "Total number of connections closed which originated from the dialer of a given name.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_closed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_failed_total",
   "type": "timeseries",
   "description": "Total number of connections failed to dial by the dialer a given name.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_established_total",
   "type": "timeseries",
   "description": "Total number of connections successfully established by the given dialer a given name.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_established_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_attempted_total",
   "type": "timeseries",
   "description": "Total number of connections attempted by the given dialer a given name.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_attempted_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "process",
 "panels": [
  {
   "title": "process_cpu_seconds_total",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "process_open_fds",
   "type": "timeseries",
   "description": "Number of open file descriptors.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_virtual_memory_max_bytes",
   "type": "timeseries",
   "description": "Maximum amount of virtual memory available in bytes.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_virtual_memory_bytes",
   "type": "timeseries",
   "description": "Virtual memory size in bytes.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "timeseries",
   "description": "Resident memory size in bytes.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_max_fds",
   "type": "timeseries",
   "description": "Maximum number of open file descriptors.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_max_fds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_start_time_seconds",
   "type": "timeseries",
   "description": "Start time of the process since unix epoch in seconds.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus",
 "panels": [
  {
   "title": "prometheus_ready",
   "type": "timeseries",
   "description": "Whether Prometheus startup was fully completed and the server is ready for normal operation.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_ready{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_template_text_expansions_total",
   "type": "timeseries",
   "description": "The total number of template text expansions.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_template_text_expansions_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_template_text_expansion_failures_total",
   "type": "timeseries",
   "description": "The total number of template text expansion failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_template_text_expansion_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_treecache_zookeeper_failures_total",
   "type": "timeseries",
   "description": "The total number of ZooKeeper failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_treecache_zookeeper_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_treecache_watcher_goroutines",
   "type": "timeseries",
   "description": "The current number of watcher goroutines.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_treecache_watcher_goroutines{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_web_federation_errors_total",
   "type": "timeseries",
   "description": "Total number of errors that occurred while sending federation responses.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_web_federation_errors_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_web_federation_warnings_total",
   "type": "timeseries",
   "description": "Total number of warnings that occurred while sending federation responses.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_web_federation_warnings_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_config_last_reload_success_timestamp_seconds",
   "type": "timeseries",
   "description": "Timestamp of the last successful configuration reload.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_success_timestamp_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_config_last_reload_successful",
   "type": "timeseries",
   "description": "Whether the last configuration reload attempt was successful.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_rule_evaluation_duration_seconds",
   "type": "timeseries",
   "description": "The duration for a rule to execute.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_rule_group_duration_seconds",
   "type": "timeseries",
   "description": "The duration of rule group evaluations.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_rule_group_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_build_info",
   "type": "timeseries",
   "description": "A metric with a constant '1' value labeled by version, revision, branch, goversion from which prometheus was built, and the goos and goarch for the build.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_build_info{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_api_remote_read_queries",
   "type": "timeseries",
   "description": "The current number of remote read queries being executed or waiting.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_api_remote_read_queries{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_engine",
 "panels": [
  {
   "title": "prometheus_engine_queries",
   "type": "timeseries",
   "description": "The current number of queries being executed or waiting.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_engine_queries{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_engine_queries_concurrent_max",
   "type": "timeseries",
   "description": "The max number of concurrent queries.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_engine_queries_concurrent_max{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_engine_query",
 "panels": [
  {
   "title": "prometheus_engine_query_duration_seconds",
   "type": "timeseries",
   "description": "Query timings",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_engine_query_log_enabled",
   "type": "timeseries",
   "description": "State of the query log.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_log_enabled{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_engine_query_log_failures_total",
   "type": "timeseries",
   "description": "The number of query log failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_log_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_http",
 "panels": [
  {
   "title": "prometheus_http_requests_total",
   "type": "timeseries",
   "description": "Counter of HTTP requests.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_http_requests_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_http_response_size_bytes",
   "type": "heatmap",
   "description": "Histogram of response size for HTTP requests.",
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_response_size_bytes{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "prometheus_http_request_duration_seconds",
   "type": "heatmap",
   "description": "Histogram of latencies for HTTP requests.",
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_request_duration_seconds{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_notifications",
 "panels": [
  {
   "title": "prometheus_notifications_queue_capacity",
   "type": "timeseries",
   "description": "The capacity of the alert notifications queue.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_notifications_queue_capacity{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_notifications_queue_length",
   "type": "timeseries",
   "description": "The number of alert notifications in the queue.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_notifications_queue_length{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_notifications_dropped_total",
   "type": "timeseries",
   "description": "Total number of alerts dropped due to errors when sending to Alertmanager.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_notifications_dropped_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_notifications_alertmanagers_discovered",
   "type": "timeseries",
   "description": "The number of alertmanagers discovered and active.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_remote_storage",
 "panels": [
  {
   "title": "prometheus_remote_storage_exemplars_in_total",
   "type": "timeseries",
   "description": "Exemplars in to remote storage, compare to exemplars out for queue managers.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_exemplars_in_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_histograms_in_total",
   "type": "timeseries",
   "description": "HistogramSamples in to remote storage, compare to histograms out for queue managers.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_histograms_in_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_samples_in_total",
   "type": "timeseries",
   "description": "Samples in to remote storage, compare to samples out for queue managers.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_in_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_string_interner_zero_reference_releases_total",
   "type": "timeseries",
   "description": "The number of times release has been called for strings that are not interned.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_string_interner_zero_reference_releases_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_highest_timestamp_in_seconds",
   "type": "timeseries",
   "description": "Highest timestamp that has come into the remote storage via the Appender interface, in seconds since epoch.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_highest_timestamp_in_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_sd",
 "panels": [
  {
   "title": "prometheus_sd_updates_total",
   "type": "timeseries",
   "description": "Total number of update events sent to the SD consumers.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_updates_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_nomad_failures_total",
   "type": "timeseries",
   "description": "Number of nomad service discovery refresh failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_nomad_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_discovered_targets",
   "type": "timeseries",
   "description": "Current number of discovered targets.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_sd_linode_failures_total",
   "type": "timeseries",
   "description": "Number of Linode service discovery refresh failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_linode_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_failed_configs",
   "type": "timeseries",
   "description": "Current number of service discovery configurations that failed to load.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_sd_failed_configs{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_sd_dns_lookup_failures_total",
   "type": "timeseries",
   "description": "The number of DNS-SD lookup failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_dns_lookup_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_dns_lookups_total",
   "type": "timeseries",
   "description": "The number of DNS-SD lookups.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_dns_lookups_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_received_updates_total",
   "type": "timeseries",
   "description": "Total number of update events received from the SD providers.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_received_updates_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_azure_failures_total",
   "type": "timeseries",
   "description": "Number of Azure service discovery refresh failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_azure_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_consul_rpc_failures_total",
   "type": "timeseries",
   "description": "The number of Consul RPC call failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_consul_rpc_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_consul_rpc_duration_seconds",
   "type": "timeseries",
   "description": "The duration of a Consul RPC call in seconds.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_sd_consul_rpc_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_sd_kubernetes_events_total",
   "type": "timeseries",
   "description": "The number of Kubernetes events handled.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_kubernetes_events_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_http_failures_total",
   "type": "timeseries",
   "description": "Number of HTTP service discovery refresh failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_http_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_sd_file",
 "panels": [
  {
   "title": "prometheus_sd_file_watcher_errors_total",
   "type": "timeseries",
   "description": "The number of File-SD errors caused by filesystem watch failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_file_watcher_errors_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_file_read_errors_total",
   "type": "timeseries",
   "description": "The number of File-SD read errors.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_file_read_errors_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_file_scan_duration_seconds",
   "type": "timeseries",
   "description": "The duration of the File-SD scan in seconds.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_sd_file_scan_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_sd_kuma_fetch",
 "panels": [
  {
   "title": "prometheus_sd_kuma_fetch_failures_total",
   "type": "timeseries",
   "description": "The number of Kuma MADS fetch call failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_kuma_fetch_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_kuma_fetch_skipped_updates_total",
   "type": "timeseries",
   "description": "The number of Kuma MADS fetch calls that result in no updates to the targets.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_sd_kuma_fetch_skipped_updates_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_kuma_fetch_duration_seconds",
   "type": "timeseries",
   "description": "The duration of a Kuma MADS fetch call.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_sd_kuma_fetch_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_target",
 "panels": [
  {
   "title": "prometheus_target_interval_length_seconds",
   "type": "timeseries",
   "description": "Actual intervals between scrapes.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_target_sync_length_seconds",
   "type": "timeseries",
   "description": "Actual interval to sync the scrape pool.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_target_sync_length_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_target_sync_failed_total",
   "type": "timeseries",
   "description": "Total number of target sync failures.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_sync_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_metadata_cache_bytes",
   "type": "timeseries",
   "description": "The number of bytes that are currently used for storing metric metadata in the cache",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "prometheus_target_metadata_cache_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_target_metadata_cache_entries",
   "type": "timeseries",
   "description": "Total number of metric metadata entries in the cache",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_target_metadata_cache_entries{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_target_scrape",
 "panels": [
  {
   "title": "prometheus_target_scrape_pools_total",
   "type": "timeseries",
   "description": "Total number of scrape pool creation attempts.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrape_pools_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrape_pools_failed_total",
   "type": "timeseries",
   "description": "Total number of scrape pool creations that failed.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrape_pools_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_target_scrape_pool",
 "panels": [
  {
   "title": "prometheus_target_scrape_pool_sync_total",
   "type": "timeseries",
   "description": "Total number of syncs that were executed on a scrape pool.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrape_pool_sync_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrape_pool_exceeded_target_limit_total",
   "type": "timeseries",
   "description": "Total number of times scrape pools hit the target limit, during sync or config reload.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrape_pool_exceeded_target_limit_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrape_pool_exceeded_label_limits_total",
   "type": "timeseries",
   "description": "Total number of times scrape pools hit the label limits, during sync or config reload.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrape_pool_exceeded_label_limits_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrape_pool_reloads_total",
   "type": "timeseries",
   "description": "Total number of scrape pool reloads.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrape_pool_reloads_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrape_pool_reloads_failed_total",
   "type": "timeseries",
   "description": "Total number of failed scrape pool reloads.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrape_pool_reloads_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrape_pool_targets",
   "type": "timeseries",
   "description": "Current number of targets in this scrape pool.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_target_scrape_pool_targets{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_target_scrapes",
 "panels": [
  {
   "title": "prometheus_target_scrapes_cache_flush_forced_total",
   "type": "timeseries",
   "description": "How many times a scrape cache was flushed due to getting big while scrapes are failing.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrapes_cache_flush_forced_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrapes_exemplar_out_of_order_total",
   "type": "timeseries",
   "description": "Total number of exemplar rejected due to not being out of the expected order.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrapes_exemplar_out_of_order_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrapes_exceeded_body_size_limit_total",
   "type": "timeseries",
   "description": "Total number of scrapes that hit the body size limit",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrapes_exceeded_body_size_limit_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrapes_exceeded_sample_limit_total",
   "type": "timeseries",
   "description": "Total number of scrapes that hit the sample limit and were rejected.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrapes_exceeded_sample_limit_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_target_scrapes_sample",
 "panels": [
  {
   "title": "prometheus_target_scrapes_sample_duplicate_timestamp_total",
   "type": "timeseries",
   "description": "Total number of samples rejected due to duplicate timestamps but different values.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrapes_sample_out_of_order_total",
   "type": "timeseries",
   "description": "Total number of samples rejected due to not being out of the expected order.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrapes_sample_out_of_order_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_target_scrapes_sample_out_of_bounds_total",
   "type": "timeseries",
   "description": "Total number of samples rejected due to timestamp falling outside of the time bounds.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrapes_sample_out_of_bounds_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb",
 "panels": [
  {
   "title": "prometheus_tsdb_tombstone_cleanup_seconds",
   "type": "heatmap",
   "description": "The time taken to recompact blocks to remove tombstones.",
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_tombstone_cleanup_seconds{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_out_of_order_samples_total",
   "type": "timeseries",
   "description": "Total number of out of order samples ingestion failed attempts due to out of order being disabled.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_out_of_order_samples_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_out_of_bound_samples_total",
   "type": "timeseries",
   "description": "Total number of out of bound samples ingestion failed attempts with out of order support disabled.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_out_of_bound_samples_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_symbol_table_size_bytes",
   "type": "timeseries",
   "description": "Size of symbol table in memory for loaded blocks",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_symbol_table_size_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_storage_blocks_bytes",
   "type": "timeseries",
   "description": "The number of bytes that are currently used for local storage by all blocks.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_retention_limit_bytes",
   "type": "timeseries",
   "description": "Max number of bytes to be retained in the tsdb blocks, configured 0 means disabled",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_retention_limit_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_snapshot_replay_error_total",
   "type": "timeseries",
   "description": "Total number snapshot replays that failed.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_snapshot_replay_error_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_data_replay_duration_seconds",
   "type": "timeseries",
   "description": "Time taken to replay the data on disk.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_data_replay_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_time_retentions_total",
   "type": "timeseries",
   "description": "The number of times that blocks were deleted because the maximum time limit was exceeded.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_time_retentions_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_reloads_failures_total",
   "type": "timeseries",
   "description": "Number of times the database failed to reloadBlocks block data from disk.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_reloads_total",
   "type": "timeseries",
   "description": "Number of times the database reloaded block data from disk.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_blocks_loaded",
   "type": "timeseries",
   "description": "Number of currently loaded data blocks",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_isolation_high_watermark",
   "type": "timeseries",
   "description": "The highest TSDB append ID that has been given out.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_isolation_high_watermark{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_isolation_low_watermark",
   "type": "timeseries",
   "description": "The lowest TSDB append ID that is still referenced.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_isolation_low_watermark{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_clean_start",
   "type": "timeseries",
   "description": "-1: lockfile is disabled. 0: a lockfile from a previous execution was replaced. 1: lockfile creation was clean",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_clean_start{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_too_old_samples_total",
   "type": "timeseries",
   "description": "Total number of out of order samples ingestion failed attempts with out of support enabled, but sample outside of time window.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_too_old_samples_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_vertical_compactions_total",
   "type": "timeseries",
   "description": "Total number of compactions done on overlapping blocks.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_vertical_compactions_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_size_retentions_total",
   "type": "timeseries",
   "description": "The number of times that blocks were deleted because the maximum number of bytes was exceeded.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_size_retentions_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_lowest_timestamp",
   "type": "timeseries",
   "description": "Lowest timestamp value stored in the database. The unit is decided by the library consumer.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_lowest_timestamp{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_mmap_chunk_corruptions_total",
   "type": "timeseries",
   "description": "Total number of memory-mapped chunk corruptions.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_mmap_chunk_corruptions_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb_checkpoint",
 "panels": [
  {
   "title": "prometheus_tsdb_checkpoint_creations_failed_total",
   "type": "timeseries",
   "description": "Total number of checkpoint creations that failed.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_checkpoint_creations_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_checkpoint_creations_total",
   "type": "timeseries",
   "description": "Total number of checkpoint creations attempted.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_checkpoint_creations_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_checkpoint_deletions_total",
   "type": "timeseries",
   "description": "Total number of checkpoint deletions attempted.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_checkpoint_deletions_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_checkpoint_deletions_failed_total",
   "type": "timeseries",
   "description": "Total number of checkpoint deletions that failed.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_checkpoint_deletions_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb_compaction",
 "panels": [
  {
   "title": "prometheus_tsdb_compaction_populating_block",
   "type": "timeseries",
   "description": "Set to 1 when a block is currently being written to the disk.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_compaction_populating_block{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_compaction_duration_seconds",
   "type": "heatmap",
   "description": "Duration of compaction runs",
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compaction_duration_seconds{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb_compaction_chunk",
 "panels": [
  {
   "title": "prometheus_tsdb_compaction_chunk_size_bytes",
   "type": "heatmap",
   "description": "Final size of chunks on their first compaction",
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compaction_chunk_size_bytes{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_compaction_chunk_samples",
   "type": "heatmap",
   "description": "Final number of samples on their first compaction",
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compaction_chunk_samples{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_compaction_chunk_range_seconds",
   "type": "heatmap",
   "description": "Final time range of chunks on their first compaction",
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compaction_chunk_range_seconds{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb_compactions",
 "panels": [
  {
   "title": "prometheus_tsdb_compactions_skipped_total",
   "type": "timeseries",
   "description": "Total number of skipped compactions due to disabled auto compaction.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_skipped_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_compactions_failed_total",
   "type": "timeseries",
   "description": "Total number of compactions that failed for the partition.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_compactions_triggered_total",
   "type": "timeseries",
   "description": "Total number of triggered compactions for the partition.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_triggered_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_compactions_total",
   "type": "timeseries",
   "description": "Total number of compactions that were executed for the partition.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb_exemplar",
 "panels": [
  {
   "title": "prometheus_tsdb_exemplar_last_exemplars_timestamp_seconds",
   "type": "timeseries",
   "description": "The timestamp of the oldest exemplar stored in circular storage. Useful to check for what timerange the current exemplar buffer limit allows. This usually means the last timestampfor all exemplars for a typical setup. This is not true though if one of the series timestamp is in future compared to rest series.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_exemplar_last_exemplars_timestamp_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_exemplar_exemplars_appended_total",
   "type": "timeseries",
   "description": "Total number of appended exemplars.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_exemplar_exemplars_appended_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_exemplar_exemplars_in_storage",
   "type": "timeseries",
   "description": "Number of exemplars currently in circular storage.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_exemplar_exemplars_in_storage{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_exemplar_out_of_order_exemplars_total",
   "type": "timeseries",
   "description": "Total number of out of order exemplar ingestion failed attempts.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_exemplar_out_of_order_exemplars_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_exemplar_max_exemplars",
   "type": "timeseries",
   "description": "Total number of exemplars the exemplar storage can store, resizeable.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_exemplar_max_exemplars{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_exemplar_series_with_exemplars_in_storage",
   "type": "timeseries",
   "description": "Number of series with exemplars currently in circular storage.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_exemplar_series_with_exemplars_in_storage{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb_head",
 "panels": [
  {
   "title": "prometheus_tsdb_head_max_time",
   "type": "timeseries",
   "description": "Maximum timestamp of the head block. The unit is decided by the library consumer.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_max_time{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_samples_appended_total",
   "type": "timeseries",
   "description": "Total number of appended samples.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_active_appenders",
   "type": "timeseries",
   "description": "Number of currently active appender transactions",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_active_appenders{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_truncations_failed_total",
   "type": "timeseries",
   "description": "Total number of head truncations that failed.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_truncations_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_truncations_total",
   "type": "timeseries",
   "description": "Total number of head truncations attempted.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_truncations_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_out_of_order_samples_appended_total",
   "type": "timeseries",
   "description": "Total number of appended out of order samples.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_out_of_order_samples_appended_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_gc_duration_seconds",
   "type": "timeseries",
   "description": "Runtime of garbage collection in the head block.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_min_time",
   "type": "timeseries",
   "description": "Minimum time bound of the head block. The unit is decided by the library consumer.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_min_time{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb_head_chunks",
 "panels": [
  {
   "title": "prometheus_tsdb_head_chunks_created_total",
   "type": "timeseries",
   "description": "Total number of chunks created in the head",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_chunks_removed_total",
   "type": "timeseries",
   "description": "Total number of chunks removed in the head",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_removed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb_head_series",
 "panels": [
  {
   "title": "prometheus_tsdb_head_series_removed_total",
   "type": "timeseries",
   "description": "Total number of series removed in the head",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_series_removed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_series_created_total",
   "type": "timeseries",
   "description": "Total number of series created in the head",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_series_created_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_series_not_found_total",
   "type": "timeseries",
   "description": "Total number of requests for series that were not found.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_series_not_found_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_tsdb_wal",
 "panels": [
  {
   "title": "prometheus_tsdb_wal_truncations_failed_total",
   "type": "timeseries",
   "description": "Total number of write log truncations that failed.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_truncations_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_wal_truncations_total",
   "type": "timeseries",
   "description": "Total number of write log truncations attempted.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_truncations_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_wal_truncate_duration_seconds",
   "type": "timeseries",
   "description": "Duration of WAL truncation.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_truncate_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_wal_segment_current",
   "type": "timeseries",
   "description": "Write log segment index that TSDB is currently writing to.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_segment_current{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_wal_fsync_duration_seconds",
   "type": "timeseries",
   "description": "Duration of write log fsync.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_fsync_duration_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_wal_writes_failed_total",
   "type": "timeseries",
   "description": "Total number of write log writes that failed.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_writes_failed_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_wal_page_flushes_total",
   "type": "timeseries",
   "description": "Total number of page flushes.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_page_flushes_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_wal_completed_pages_total",
   "type": "timeseries",
   "description": "Total number of completed pages.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_completed_pages_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_wal_corruptions_total",
   "type": "timeseries",
   "description": "Total number of WAL corruptions.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_corruptions_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "promhttp",
 "panels": [
  {
   "title": "promhttp_metric_handler_requests_in_flight",
   "type": "timeseries",
   "description": "Current number of scrapes being served.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_in_flight{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "promhttp_metric_handler_requests_total",
   "type": "timeseries",
   "description": "Total number of scrapes by HTTP status code.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}