{
 "title": "prochain_executor",
 "panels": [
  {
   "title": "prochain_executor_rust_bot_start",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_rust_bot_start{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prochain_executor_gateio",
 "panels": [
  {
   "title": "prochain_executor_gateio_pending_logs_trx_count",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_pending_logs_trx_count{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_pending_logs_call_websocket_count",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prochain_executor_gateio_pending_logs_call_websocket_count{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_state_refresh_duration",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_state_refresh_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_state_pool_number",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_state_pool_number{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prochain_executor_gateio_markets",
 "panels": [
  {
   "title": "prochain_executor_gateio_markets_update_count",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prochain_executor_gateio_markets_update_count{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_markets_symbol_sol_usdt",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_markets_symbol_sol_usdt{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_markets_symbol_btc_usdt",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_markets_symbol_btc_usdt{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prochain_executor_gateio_trx",
 "panels": [
  {
   "title": "prochain_executor_gateio_trx_block_possible_opportunity_simulation_minamount",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_block_possible_opportunity_simulation_minamount{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prochain_executor_gateio_trx_long_possible_opportunity",
 "panels": [
  {
   "title": "prochain_executor_gateio_trx_long_possible_opportunity_gas",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_long_possible_opportunity_gas{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_long_possible_opportunity_gas_price",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_long_possible_opportunity_gas_price{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prochain_executor_gateio_trx_long_possible_opportunity_event",
 "panels": [
  {
   "title": "prochain_executor_gateio_trx_long_possible_opportunity_event_percent",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_long_possible_opportunity_event_percent{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_long_possible_opportunity_event_win_usdt",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_long_possible_opportunity_event_win_usdt{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_long_possible_opportunity_event_counter",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prochain_executor_gateio_trx_long_possible_opportunity_event_counter{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prochain_executor_gateio_trx_pending_possible_opportunity",
 "panels": [
  {
   "title": "prochain_executor_gateio_trx_pending_possible_opportunity_gas",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_pending_possible_opportunity_gas{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_pending_possible_opportunity_gas_price",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_pending_possible_opportunity_gas_price{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_pending_possible_opportunity_simulation_minamount",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_pending_possible_opportunity_simulation_minamount{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prochain_executor_gateio_trx_pending_possible_opportunity_event",
 "panels": [
  {
   "title": "prochain_executor_gateio_trx_pending_possible_opportunity_event_counter",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prochain_executor_gateio_trx_pending_possible_opportunity_event_counter{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_pending_possible_opportunity_event_percent",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_pending_possible_opportunity_event_percent{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_pending_possible_opportunity_event_win_usdt",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_pending_possible_opportunity_event_win_usdt{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prochain_executor_gateio_trx_triggered",
 "panels": [
  {
   "title": "prochain_executor_gateio_trx_triggered_block_counter",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prochain_executor_gateio_trx_triggered_block_counter{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_triggered_pending_counter",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prochain_executor_gateio_trx_triggered_pending_counter{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_triggered_counter",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prochain_executor_gateio_trx_triggered_counter{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "prochain_executor_gateio_trx_triggered_event",
 "panels": [
  {
   "title": "prochain_executor_gateio_trx_triggered_event_gas_price_init_usdt",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_triggered_event_gas_price_init_usdt{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_triggered_event_gas_init_usdt",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_triggered_event_gas_init_usdt{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_executor_gateio_trx_triggered_event_win_init_usdt",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_executor_gateio_trx_triggered_event_win_init_usdt{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}