{
 "title": "dotnet",
 "panels": [
  {
   "title": "dotnet_collection_count_total",
   "type": "timeseries",
   "description": "GC collection count",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dotnet_collection_count_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "dotnet_total_memory_bytes",
   "type": "timeseries",
   "description": "Total known allocated memory",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "microsoft_aspnetcore",
 "panels": [
  {
   "title": "microsoft_aspnetcore_routing_aspnetcore_routing_match_attempts",
   "type": "timeseries",
   "description": "({match_attempt}) Number of requests that were attempted to be matched to an endpoint. (Counter`1)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_routing_aspnetcore_routing_match_attempts{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "microsoft_aspnetcore_hosting",
 "panels": [
  {
   "title": "microsoft_aspnetcore_hosting_failed_requests",
   "type": "timeseries",
   "description": "Failed Requests",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_failed_requests{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_hosting_total_requests",
   "type": "timeseries",
   "description": "Total Requests",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_total_requests{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_hosting_current_requests",
   "type": "timeseries",
   "description": "Current Requests",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_current_requests{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_hosting_http_server_request_duration",
   "type": "heatmap",
   "description": "(s) Duration of HTTP server requests. (Histogram`1)",
   "targets": [
    {
     "expr": "sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_hosting_http_server_active_requests",
   "type": "timeseries",
   "description": "({request}) Number of active HTTP server requests. (UpDownCounter`1)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_active_requests{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_hosting_requests_per_second_total",
   "type": "timeseries",
   "description": "Request Rate",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_hosting_requests_per_second_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}
{
 "title": "microsoft_aspnetcore_http_connections",
 "panels": [
  {
   "title": "microsoft_aspnetcore_http_connections_current_connections",
   "type": "timeseries",
   "description": "Current Connections",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_http_connections_current_connections{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_http_connections_signalr_server_active_connections",
   "type": "timeseries",
   "description": "({connection}) Number of connections that are currently active on the server. (UpDownCounter`1)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_http_connections_signalr_server_active_connections{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "microsoft_aspnetcore_http_connections_connections",
 "panels": [
  {
   "title": "microsoft_aspnetcore_http_connections_connections_started",
   "type": "timeseries",
   "description": "Total Connections Started",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_http_connections_connections_started{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_http_connections_connections_stopped",
   "type": "timeseries",
   "description": "Total Connections Stopped",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_http_connections_connections_stopped{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_http_connections_connections_duration",
   "type": "timeseries",
   "description": "(ms) Average Connection Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_http_connections_connections_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_http_connections_connections_timed_out",
   "type": "timeseries",
   "description": "Total Connections Timed Out",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_http_connections_connections_timed_out{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "microsoft_aspnetcore_server_kestrel",
 "panels": [
  {
   "title": "microsoft_aspnetcore_server_kestrel_connections_per_second_total",
   "type": "timeseries",
   "description": "Connection Rate",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_server_kestrel_connections_per_second_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_total_connections",
   "type": "timeseries",
   "description": "Total Connections",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_total_connections{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_total_tls_handshakes",
   "type": "timeseries",
   "description": "Total TLS Handshakes",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_total_tls_handshakes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_tls_handshakes_per_second_total",
   "type": "timeseries",
   "description": "TLS Handshake Rate",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_server_kestrel_tls_handshakes_per_second_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_failed_tls_handshakes",
   "type": "timeseries",
   "description": "Failed TLS Handshakes",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_failed_tls_handshakes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_connection_queue_length",
   "type": "timeseries",
   "description": "Connection Queue Length",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_connection_queue_length{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_request_queue_length",
   "type": "timeseries",
   "description": "Request Queue Length",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_request_queue_length{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "microsoft_aspnetcore_server_kestrel_current",
 "panels": [
  {
   "title": "microsoft_aspnetcore_server_kestrel_current_connections",
   "type": "timeseries",
   "description": "Current Connections",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_current_connections{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_current_upgraded_requests",
   "type": "timeseries",
   "description": "Current Upgraded Requests (WebSockets)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_current_upgraded_requests{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_current_tls_handshakes",
   "type": "timeseries",
   "description": "Current TLS Handshakes",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_current_tls_handshakes{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "microsoft_aspnetcore_server_kestrel_kestrel",
 "panels": [
  {
   "title": "microsoft_aspnetcore_server_kestrel_kestrel_upgraded_connections",
   "type": "timeseries",
   "description": "({connection}) Number of HTTP connections that are currently upgraded (WebSockets). The number only tracks HTTP/1.1 connections. (UpDownCounter`1)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_kestrel_upgraded_connections{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_kestrel_connection_duration",
   "type": "heatmap",
   "description": "(s) The duration of connections on the server. (Histogram`1)",
   "targets": [
    {
     "expr": "sum(rate(microsoft_aspnetcore_server_kestrel_kestrel_connection_duration{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_kestrel_queued_connections",
   "type": "timeseries",
   "description": "({connection}) Number of connections that are currently queued and are waiting to start. (UpDownCounter`1)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_kestrel_queued_connections{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "microsoft_aspnetcore_server_kestrel_kestrel_active_connections",
   "type": "timeseries",
   "description": "({connection}) Number of connections that are currently active on the server. (UpDownCounter`1)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_kestrel_active_connections{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "process",
 "panels": [
  {
   "title": "process_open_handles",
   "type": "timeseries",
   "description": "Number of open handles",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_handles{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_private_memory_bytes",
   "type": "timeseries",
   "description": "Process private memory size",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_private_memory_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_virtual_memory_bytes",
   "type": "timeseries",
   "description": "Virtual memory size in bytes.",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_num_threads",
   "type": "timeseries",
   "description": "Total number of threads",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_num_threads{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_start_time_seconds",
   "type": "timeseries",
   "description": "Start time of the process since unix epoch in seconds.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "process_working_set_bytes",
   "type": "timeseries",
   "description": "Process working set",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prochain_spotapi_exchange_dotnet",
 "panels": [
  {
   "title": "prochain_spotapi_exchange_dotnet_markets_time_refresh_histo",
   "type": "heatmap",
   "description": "Histogram of time refreshed gateio market data.",
   "targets": [
    {
     "expr": "sum(rate(prochain_spotapi_exchange_dotnet_markets_time_refresh_histo{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  }
 ]
}
{
 "title": "prochain_spotapi_exchange_dotnet_market",
 "panels": [
  {
   "title": "prochain_spotapi_exchange_dotnet_market_bids_number_gauge",
   "type": "timeseries",
   "description": "Gauge number bids",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_spotapi_exchange_dotnet_market_bids_number_gauge{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_spotapi_exchange_dotnet_market_asks_number_gauge",
   "type": "timeseries",
   "description": "Gauge number asks",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prochain_spotapi_exchange_dotnet_market_asks_number_gauge{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prochain_spotapi_exchange_dotnet_market_best_bids",
   "type": "heatmap",
   "description": "Histogram of time refreshed gateio market data.",
   "targets": [
    {
     "expr": "sum(rate(prochain_spotapi_exchange_dotnet_market_best_bids{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "prochain_spotapi_exchange_dotnet_market_best_asks",
   "type": "heatmap",
   "description": "Histogram of time refreshed gateio market data.",
   "targets": [
    {
     "expr": "sum(rate(prochain_spotapi_exchange_dotnet_market_best_asks{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_net",
 "panels": [
  {
   "title": "prometheus_net_meteradapter_instruments_connected",
   "type": "timeseries",
   "description": "Number of instruments that are currently connected to the adapter.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_net_meteradapter_instruments_connected{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_net_exemplars_recorded_total",
   "type": "timeseries",
   "description": "Number of exemplars that were accepted into in-memory storage in the prometheus-net SDK.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_net_exemplars_recorded_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "prometheus_net_eventcounteradapter_sources_connected_total",
   "type": "timeseries",
   "description": "Number of event sources that are currently connected to the adapter.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_net_eventcounteradapter_sources_connected_total{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "prometheus_net_metric",
 "panels": [
  {
   "title": "prometheus_net_metric_families",
   "type": "timeseries",
   "description": "Number of metric families currently registered.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_net_metric_families{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_net_metric_instances",
   "type": "timeseries",
   "description": "Number of metric instances currently registered across all metric families.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_net_metric_instances{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "prometheus_net_metric_timeseries",
   "type": "timeseries",
   "description": "Number of metric timeseries currently generated from all metric instances.",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_net_metric_timeseries{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_net_http",
 "panels": [
  {
   "title": "system_net_http_http11_requests_queue_duration",
   "type": "timeseries",
   "description": "(ms) HTTP 1.1 Requests Queue Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_http11_requests_queue_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_http_http11_connections_current_total",
   "type": "timeseries",
   "description": "Current Http 1.1 Connections",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_http11_connections_current_total{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_http_http20_connections_current_total",
   "type": "timeseries",
   "description": "Current Http 2.0 Connections",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_http20_connections_current_total{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_http_http20_requests_queue_duration",
   "type": "timeseries",
   "description": "(ms) HTTP 2.0 Requests Queue Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_http20_requests_queue_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_http_current_requests",
   "type": "timeseries",
   "description": "Current Requests",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_current_requests{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_http_http30_requests_queue_duration",
   "type": "timeseries",
   "description": "(ms) HTTP 3.0 Requests Queue Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_http30_requests_queue_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_http_http30_connections_current_total",
   "type": "timeseries",
   "description": "Current Http 3.0 Connections",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_http30_connections_current_total{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_http_requests_failed",
   "type": "timeseries",
   "description": "Requests Failed",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_requests_failed{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_http_requests_started",
   "type": "timeseries",
   "description": "Requests Started",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_requests_started{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_net_http_http_client",
 "panels": [
  {
   "title": "system_net_http_http_client_request_time_in_queue",
   "type": "heatmap",
   "description": "(s) The amount of time requests spent on a queue waiting for an available connection. (Histogram`1)",
   "targets": [
    {
     "expr": "sum(rate(system_net_http_http_client_request_time_in_queue{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "system_net_http_http_client_request_duration",
   "type": "heatmap",
   "description": "(s) The duration of outbound HTTP requests. (Histogram`1)",
   "targets": [
    {
     "expr": "sum(rate(system_net_http_http_client_request_duration{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "system_net_http_http_client_active_requests",
   "type": "timeseries",
   "description": "({request}) Number of outbound HTTP requests that are currently active on the client. (UpDownCounter`1)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_http_client_active_requests{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_http_http_client_connection_duration",
   "type": "heatmap",
   "description": "(s) The duration of successfully established outbound HTTP connections. (Histogram`1)",
   "targets": [
    {
     "expr": "sum(rate(system_net_http_http_client_connection_duration{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "system_net_http_http_client_open_connections",
   "type": "timeseries",
   "description": "({connection}) Number of outbound HTTP connections that are currently active or idle on the client. (UpDownCounter`1)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_http_http_client_open_connections{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_net_nameresolution",
 "panels": [
  {
   "title": "system_net_nameresolution_current_dns_lookups",
   "type": "timeseries",
   "description": "Current DNS Lookups",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_nameresolution_current_dns_lookups{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_net_nameresolution_dns",
 "panels": [
  {
   "title": "system_net_nameresolution_dns_lookup_duration",
   "type": "heatmap",
   "description": "(s) Measures the time taken to perform a DNS lookup. (Histogram`1)",
   "targets": [
    {
     "expr": "sum(rate(system_net_nameresolution_dns_lookup_duration{job=~'$job',instance=~'$instance'}[3m])) by (le)"
    }
   ]
  },
  {
   "title": "system_net_nameresolution_dns_lookups_duration",
   "type": "timeseries",
   "description": "(ms) Average DNS Lookup Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_nameresolution_dns_lookups_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_nameresolution_dns_lookups_requested",
   "type": "timeseries",
   "description": "DNS Lookups Requested",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_nameresolution_dns_lookups_requested{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_net_security",
 "panels": [
  {
   "title": "system_net_security_all_tls_sessions_open",
   "type": "timeseries",
   "description": "All TLS Sessions Active",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_all_tls_sessions_open{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_all_tls_handshake_duration",
   "type": "timeseries",
   "description": "(ms) TLS Handshake Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_all_tls_handshake_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_tls10_sessions_open",
   "type": "timeseries",
   "description": "TLS 1.0 Sessions Active",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_tls10_sessions_open{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_tls10_handshake_duration",
   "type": "timeseries",
   "description": "(ms) TLS 1.0 Handshake Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_tls10_handshake_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_tls12_handshake_duration",
   "type": "timeseries",
   "description": "(ms) TLS 1.2 Handshake Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_tls12_handshake_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_tls12_sessions_open",
   "type": "timeseries",
   "description": "TLS 1.2 Sessions Active",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_tls12_sessions_open{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_tls11_handshake_duration",
   "type": "timeseries",
   "description": "(ms) TLS 1.1 Handshake Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_tls11_handshake_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_tls11_sessions_open",
   "type": "timeseries",
   "description": "TLS 1.1 Sessions Active",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_tls11_sessions_open{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_tls_handshake_total",
   "type": "timeseries",
   "description": "TLS handshakes completed",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_net_security_tls_handshake_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_net_security_tls13_sessions_open",
   "type": "timeseries",
   "description": "TLS 1.3 Sessions Active",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_tls13_sessions_open{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_tls13_handshake_duration",
   "type": "timeseries",
   "description": "(ms) TLS 1.3 Handshake Duration",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_tls13_handshake_duration{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_failed_tls_handshakes",
   "type": "timeseries",
   "description": "Total TLS handshakes failed",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_failed_tls_handshakes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_total_tls_handshakes",
   "type": "timeseries",
   "description": "Total TLS handshakes completed",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_total_tls_handshakes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_security_current_tls_handshakes",
   "type": "timeseries",
   "description": "Current TLS handshakes",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_security_current_tls_handshakes{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_net_sockets",
 "panels": [
  {
   "title": "system_net_sockets_current_outgoing_connect_attempts",
   "type": "timeseries",
   "description": "Current Outgoing Connect Attempts",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_sockets_current_outgoing_connect_attempts{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_sockets_datagrams_sent",
   "type": "timeseries",
   "description": "Datagrams Sent",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_sockets_datagrams_sent{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_sockets_datagrams_received",
   "type": "timeseries",
   "description": "Datagrams Received",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_sockets_datagrams_received{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_sockets_bytes_sent",
   "type": "timeseries",
   "description": "Bytes Sent",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_sent{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_sockets_bytes_received",
   "type": "timeseries",
   "description": "Bytes Received",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_net_sockets_bytes_received{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_sockets_outgoing_connections_established",
   "type": "timeseries",
   "description": "Outgoing Connections Established",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_sockets_outgoing_connections_established{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_net_sockets_incoming_connections_established",
   "type": "timeseries",
   "description": "Incoming Connections Established",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_net_sockets_incoming_connections_established{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_runtime",
 "panels": [
  {
   "title": "system_runtime_time_in_jit_total",
   "type": "timeseries",
   "description": "(ms) Time spent in JIT",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_runtime_time_in_jit_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_runtime_time_in_gc",
   "type": "timeseries",
   "description": "(%) % Time in GC since last GC",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_time_in_gc{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_poh_size",
   "type": "timeseries",
   "description": "(B) POH (Pinned Object Heap) Size",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_poh_size{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_il_bytes_jitted",
   "type": "timeseries",
   "description": "(B) IL Bytes Jitted",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_runtime_il_bytes_jitted{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_cpu_usage",
   "type": "timeseries",
   "description": "(%) CPU Usage",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_exception_count_total",
   "type": "timeseries",
   "description": "Exception Count",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_runtime_exception_count_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_runtime_working_set",
   "type": "timeseries",
   "description": "(MB) Working Set",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_working_set{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_loh_size",
   "type": "timeseries",
   "description": "(B) LOH Size",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_loh_size{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_active_timer_count",
   "type": "timeseries",
   "description": "Number of Active Timers",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_active_timer_count{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_alloc_total",
   "type": "timeseries",
   "description": "(B) Allocation Rate",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_runtime_alloc_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_runtime_monitor_lock_contention_count_total",
   "type": "timeseries",
   "description": "Monitor Lock Contention Count",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_runtime_monitor_lock_contention_count_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_runtime_methods_jitted_count",
   "type": "timeseries",
   "description": "Number of Methods Jitted",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_methods_jitted_count{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_total_pause_time_by_gc_total",
   "type": "timeseries",
   "description": "(ms) Time paused by GC",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_runtime_total_pause_time_by_gc_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_runtime_assembly_count",
   "type": "timeseries",
   "description": "Number of Assemblies Loaded",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_assembly_count{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_runtime_gc",
 "panels": [
  {
   "title": "system_runtime_gc_heap_size",
   "type": "timeseries",
   "description": "(MB) GC Heap Size",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_gc_heap_size{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_gc_committed",
   "type": "timeseries",
   "description": "(MB) GC Committed Bytes",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_gc_committed{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_gc_fragmentation",
   "type": "timeseries",
   "description": "(%) GC Fragmentation",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_gc_fragmentation{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_runtime_gen",
 "panels": [
  {
   "title": "system_runtime_gen_1_size",
   "type": "timeseries",
   "description": "(B) Gen 1 Size",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_gen_1_size{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_gen_1_gc_count_total",
   "type": "timeseries",
   "description": "Gen 1 GC Count",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_runtime_gen_1_gc_count_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_runtime_gen_2_gc_count_total",
   "type": "timeseries",
   "description": "Gen 2 GC Count",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_runtime_gen_2_gc_count_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_runtime_gen_2_size",
   "type": "timeseries",
   "description": "(B) Gen 2 Size",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_gen_2_size{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_runtime_gen_0",
 "panels": [
  {
   "title": "system_runtime_gen_0_size",
   "type": "timeseries",
   "description": "(B) Gen 0 Size",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_gen_0_size{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_gen_0_gc_count_total",
   "type": "timeseries",
   "description": "Gen 0 GC Count",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_runtime_gen_0_gc_count_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_runtime_gen_0_gc_budget",
   "type": "timeseries",
   "description": "(MB) Gen 0 GC Budget",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_gen_0_gc_budget{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}
{
 "title": "system_runtime_threadpool",
 "panels": [
  {
   "title": "system_runtime_threadpool_completed_items_count_total",
   "type": "timeseries",
   "description": "ThreadPool Completed Work Item Count",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_runtime_threadpool_completed_items_count_total{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "system_runtime_threadpool_thread_count",
   "type": "timeseries",
   "description": "ThreadPool Thread Count",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_threadpool_thread_count{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system_runtime_threadpool_queue_length",
   "type": "timeseries",
   "description": "ThreadPool Queue Length",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_runtime_threadpool_queue_length{job=~'$job',instance=~'$instance'}"
    }
   ]
  }
 ]
}